title: 
  ru: Частный кибердетектив Денис Кудин
  en: Private Cyberdetective Dennis Kudin
email: dennis@kudin.net
description: 
  ru: Услуги частного кибердетектива в Украине. Комплексный подход к защите информации
  en: Complex services for information protection
index:
  ru: /
  en: /en/
baseurl: "" 
url: "" 
twitter_username: denkudin
github_username:  denkudin

# Build settings
markdown: kramdown
timezone: Europe/Kiev
theme: jekyll-theme-leap-day
destination: _site
plugins:
  - jekyll-feed
