title: 
  ua: "Приватний кібердетектив Денис Кудін"
  en: "Private Cyberdetective Dennis Kudin"
email: dennis@kudin.net
description:
  ua: "Послуги приватного кібердетектива в Україні. Комплексний підхід до захисту інформації"
  en: "Complex services for information protection"
index:
  ua: /
  en: en
baseurl: "" 
url: "https://denkudin.github.io" 
twitter_username: denkudin
github_username:  denkudin

# Build settings
markdown: kramdown
timezone: Europe/Kiev
theme: jekyll-theme-leap-day
destination: _site
plugins:
  - jekyll-feed
